---
- name: Deploy Zabbix stack on EKS
  hosts: eks_control
  gather_facts: false

  pre_tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        context: "{{ kube_context | default(omit) }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ zabbix_namespace }}"

  roles:
    - role: mysql
    - role: zabbix
    - role: haproxy
    - role: grafana
